name: 'Infrastructure as Code (IaC)'
on:
  push:
    branches: [ "main", "develop" ]
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'
  pull_request:
    branches: [ "main", "develop" ]
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform.yml'

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: 'Infrastructure as Code (IaC) - Terraform'
    runs-on: ubuntu-latest
    environment: ${{ (github.base_ref == 'main' || github.ref_name == 'main') && 'stage' || 'development' }}
    env:
      TF_LOG: INFO
      TF_IN_AUTOMATION: true
      ENV_DIR: ${{ (github.base_ref == 'main' || github.ref_name == 'main')  && 'stage' || 'development' }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_USE_OIDC: true
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      AWS_REGION: ${{ vars.AWS_REGION }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform/environments/${{ env.ENV_DIR }}

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 #v7.0.0

  # Configure AWS credentials to allow Terraform to assume a role in the target AWS account
    - name : Configure AWS Credentials
      if: ${{ (github.base_ref == 'develop' || github.ref_name == 'develop') }}
      uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
      with:
        role-to-assume: ${{ env.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      if: ${{ (github.base_ref == 'develop' || github.ref_name == 'develop') }}
      uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e #v4.0.1
      with:
        terraform_version: 1.15.6

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      if: ${{ (github.base_ref == 'develop' || github.ref_name == 'develop') }}
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      if: ${{ (github.base_ref == 'develop' || github.ref_name == 'develop') }}
      run: terraform fmt -check

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      env:
        ARM_PROVIDER_ENHANCED_VALIDATION: "false"
      if: ${{ (github.base_ref == 'develop' || github.ref_name == 'develop') }}
      run: terraform plan -input=false -out=tfplan && terraform show -json tfplan | jq . > tfplan-${{ env.ENV_DIR }}.json

